### ISSUE TITLE
Crash after intro

### ISSUE THREAD

**Issue by Fan4eGGG** [Zurek0x/ZombiU_XPatcher#1]
just do with ur guide and after logo "how long u survive" I have CTD wo/errors.

**Comment by Zurek0x** [comment]
Make sure you copy all files from the "contents" folder to your main game directory.
Next run the "setup.bat" file "AS ADMINISTRATOR < IMPORTANT" and let it setup.

Then try again.

_**Path Instructions below**_
`
How To Patch

1. Download the full source off Github
2. Extract all the contents from the folder labeled "contents/Version X.X" to your ZOMBI/U INSTALLATION DIRECTORY
3. Replace any files if needed, If you want too you can back-up your files before starting
4. After replacing all the files run the file <Patch.bat> AS ADMINISTRATOR
5. After doing so follow the on-screen instructions
6. Once everything is done launch up the game and begin!
7. `

**Comment by Fan4eGGG** [comment]
there is no "setup.bat" only "patch.bat".
next, problem is in ur .exe. cuz i backup the orig .exe and after CTD i restore and it works perfect. but wo/gun and shot sound, but still.

**Comment by Zurek0x** [comment]
> there is no "setup.bat" only "patch.bat". next, problem is in ur .exe. cuz i backup the orig .exe and after CTD i restore and it works perfect. but wo/gun and shot sound, but still.

You want to replace all files with the ones from the _**contents/Version X.X**_ , And I meant to say **path.bat**

**Comment by Fan4eGGG** [comment]
man, I did all with ur guide. it didnt work.

**Comment by Zurek0x** [comment]
> man, I did all with ur guide. it didnt work.

[Zombi - ZombiU Sound Bug Fix + Other Bug Fixes [Mod]
](https://www.youtube.com/watch?v=LV_hlMwbl58)
Watch this guide

**Comment by Fan4eGGG** [comment]
ur kidding?
problem in .exe file in ur archive. fix it.

**Comment by Zurek0x** [comment]
> ur kidding? problem in .exe file in ur archive. fix it.

So for now I will have to re-test our program including the patch, We will do a full re-path on a test machine we have and use, For now You will have to wait as we need to clear the games registry on our PC's end and also re-install the game. We will notify you on our tests in the next 30 Mintues to 1 Hour.

The reason we have to do this is that this project for the most part is working but mostly abandoned and won't recieve any updates unless they are critical updates, We only really plan to update this when the path stops working or once we release a more efficient way of Modifying the games instructions.

**Comment by Zurek0x** [comment]
> ur kidding? problem in .exe file in ur archive. fix it.

Also please provide more information.

**Comment by Fan4eGGG** [comment]
installed the game from steam. I installed ur mod according to your instructions, I start the game from steam - after the intro it crashes to the desktop.
by the way, reshade was installed, but the problem was not in it, because after that I reinstalled the game completely and without reshade - the result is the same.

I also tried to remove the chromatic aberration effect through the method on PCGAMINGWIKI, but w/it and wo/it still crashes to the desktop. after replacing yours .**exe** to the original, the game starts and plays normally, only without sounds.
thats all.

**Comment by Fan4eGGG** [comment]
and so? how are things going?
 I tried again to put a clean game on the pirate and on the Steam version - the result is the same. the problem is in **.exe**

**Comment by Zurek0x** [comment]
> and so? how are things going? I tried again to put a clean game on the pirate and on the Steam version - the result is the same. the problem is in **.exe**

Sorry I took so long, I was away for a few days (Personal Stuff) and just got back.
So we ran through the Patch/Install again of the patch and so far came back OK.

We didn't experience any issues that you listed, We tested on our main PC and a fresh installation of Windows 10 & 11 and had no issues so far.

Some things I would suggest you do is check the following

+ Make sure you are inputting the correct installation path of your ZOMBI game directory when running the "patch.bat"
![image](https://user-images.githubusercontent.com/32526701/188938004-06f2123c-c12c-4417-997f-dd83cf308036.png)
( Mine is installed on my steamapps in my C Drive )
+ Make sure you run the "patch.bat" as Administrator (Right Click, Run as administrator)
+ Make sure you replace all files (if asked)
+ Make sure you are on the official version of ZOMBI from Steam or Ubisoft (Not Cracked)
+ Make sure you have the leatest C++ Redist from Microsoft >> https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/
+ Make sure you have installed the leatest version of DotNET / .NET >> https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.8-windows-x64-installer

**Comment by Zurek0x** [comment]
I will be closing this ticket as there is nothing we can do on our end and is a issue with your game/system specifically.
We do testing and make sure our software works and is compatible with almost every machine.

Either you are not following the install instructions correctly or there is a issue with your system/OS.
Thank you for opening a ticket and we enjoy all feedback we can get!

**Comment by Fan4eGGG** [comment]
probably, I've been speaking incorrectly all this time, or you misunderstood me. 
I meant that if you don't transfer your **.exe** from your archive, and patch the game with the original **.exe** - then everything _works correctly_. the problem was exactly in your **.exe**. with the original, everything works correctly.

anyway, thanks for the help.

**Comment by tqoac** [comment]
> probably, I've been speaking incorrectly all this time, or you misunderstood me. I meant that if you don't transfer your **.exe** from your archive, and patch the game with the original **.exe** - then everything _works correctly_. the problem was exactly in your **.exe**. with the original, everything works correctly.
> 
> anyway, thanks for the help.

Try switching ubisoft connect to offline mode, it should circumvent the crash, worked for me.

**Comment by Fan4eGGG** [comment]
> Try switching ubisoft connect to offline mode, it should circumvent the crash, worked for me.

I passed the game 2 weeks ago, so I dont need it anymore (:
but thanks for the advice.
